### PR TITLE
Revert "Yeet more garbage"

### PR DESCRIPTION
**Pull request by halotroop2288**
This reverts commit d92a366d19540afb7fa627484db5c25e9c9034f8, which removed pages for seemingly no reason, and replaced some of them with ugly single-line pages that would have been better suited for redirects had there been any consensus to do so anyway.

### CODE REVIEW

**Comment by Margen67** [comment]
These should be made into proper redirects. As for your improvements to the documents, you should make a PR for them on xenia. There's no need to have the same docs in multiple places.

The `hacks and mods` page and `build tweaks` were deleted for a reason: They're garbage. They've been obsoleted by https://github.com/xenia-canary/game-patches/

**Comment by halotroop2288** [comment]
[Again](https://github.com/xenia-project/wiki/commit/d92a366d19540afb7fa627484db5c25e9c9034f8#r88897373), no. This documentation is not a duplicate of the previous documentation, and its improvements cannot be applied to GitHub-flavored Markdown.
The entire purpose of having a wiki is to have one central place for this information. If anything, other pages should link back to the wiki, not the other way around.

**Comment by Margen67** [comment]
> [Again](https://github.com/xenia-project/wiki/commit/d92a366d19540afb7fa627484db5c25e9c9034f8#r88897373), no. This documentation is not a duplicate of the previous documentation, and its improvements cannot be applied to GitHub-flavored Markdown. The entire purpose of having a wiki is to have one central place for this information. If anything, other pages should link back to the wiki, not the other way around.

Then the wiki should be linked from the docs on the xenia repository to prevent confusion. Doing it the way you want to just causes unneeded fragmentation.

**Comment by halotroop2288** [comment]
> the wiki should be linked from the docs on the xenia repository

Yes. Of course. But I'm not in control of those docs whatsoever. It's up to the discretion of the Xenia maintainers to do that.

**Comment by Margen67** [comment]
> > the wiki should be linked from the docs on the xenia repository
> 
> Yes. Of course. But I'm not in control of those docs whatsoever. It's up to the discretion of the Xenia maintainers to do that.

Can you make a PR to the xenia repository?

**Comment by halotroop2288** [comment]
> Can you make a PR to the xenia repository?

Yes, and so can you. That's what you should have done to begin with, rather than deleting these pages just because you could.

**Comment by Margen67** [comment]
> > Can you make a PR to the xenia repository?
> 
> Yes, and so can you. That's what you should have done to begin with, rather than deleting these pages just because you could.

Correction: That's what **you** should have done to begin with.
I don't understand why you think having two copies of a page without redirecting the old one to the new one is a good idea.
How is anyone supposed to know which one they're supposed to be editing?

I just checked and as far as I can tell they're all 1:1 except for building.md:
 

Even *if* we wanted to merge this PR it would've just made a bigger mess regardless;
 * `building.md` is outdated; It mentions the wrong Windows SDK, and doesn't mention the VS2022 bug.
   * `building.md` on the xenia master repository still wouldn't have linked to the new one.
 * Hacks and mods page has been obsoleted by [xenia-canary/game-patches](https://github.com/xenia-canary/game-patches).
 * The 4:3 build tweak doesn't even work.
 * The compatibility list is never going to be on the wiki. That's not where it belongs.

**Pull request closed without merging**
